kind: wasmer.io/App.v0
owner: WoompaLoompa
name: prestashop
package: .

scaling:
  mode: single_concurrency

capabilities:
  database:
    engine: mysql
  instaboot:
    requests:
      - path: /

locality:
  regions:
    - fr-roub1

env:
  ADMIN_MAIL: "admin@example.com"
  ADMIN_PASSWD: "Pr3st4Sh0P"
  DB_SERVER: "mysql"
  DB_PORT: "3306"
  DB_USER: "root"
  DB_PASSWD: "prestashop"
  DB_NAME: "prestashop"
  DB_PREFIX: "ps_"
  PS_DOMAIN: "prestashop-clink.wasmer.io"
  PS_FOLDER_INSTALL: "install-dev"
  PS_FOLDER_ADMIN: "admin-dev"
  PS_COUNTRY: "fr"
  PS_LANGUAGE: "en"
  PS_DEV_MODE: "1"
  PS_ENABLE_SSL: "0"
  PS_ERASE_DB: "1"
  PS_INSTALL_AUTO: "1"
  PS_USE_DOCKER_MAILDEV: "0"
  PS_INSTALL_DEMO_PRODUCTS: "0"
  DISABLE_MAKE: "0"
  PS_DEMO_MODE: "0"
  BLACKFIRE_ENABLE: "0"
